### PR TITLE
Make permissions dispatcher work again

### PR DESCRIPTION
**Pull request by shiraji**
This will generate `PostEditFragmentPermissionsDispatcher`

see https://github.com/hotchemi/PermissionsDispatcher/issues/270#issuecomment-279283213

### CODE REVIEW

**Comment by vickychijwani** [comment]
Thanks for initiating this, I'll need to do add some more commits on top of this to work with Realm 2.x.

**Comment by vickychijwani** [comment]
This is blocked by #112

**Comment by shiraji** [comment]
As I comment before, Realm v1.2.0 won't fix this issue. I haven't tested v2.x except v2.3.1. Since I'm not familiar with Realm, I let you decide which version you guys use. Feel free to use/ditch my commit!

By the way, thanks for reporting detail issue. That helps us a lot. Also, thanks for picking our library for handling Runtime Permissions. We feel really good when apps like `quill` uses our library.

**Comment by vickychijwani** [comment]
Fixed in #112 and #119. Thanks for the help @shiraji!

**Pull request closed without merging**
